### ISSUE TITLE
we should be aware that database with all passwords is exposed, it should not be public unless purged

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-chart#13]
especially since kyiv instance is public @dsavchenko

**Comment by volodymyrss** [comment]
at least drupal admin should be updated https://github.com/oda-hub/frontend-chart/blob/master/make.sh#L79

**Comment by dsavchenko** [comment]
Yes, this is what I also wrote about
https://github.com/oda-hub/frontend-drupal7-db-for-astrooda/issues/5

**Comment by dsavchenko** [comment]
Also, I hope db password [here](https://github.com/oda-hub/frontend-drupal7-for-astrooda/blob/7ef15ee33477edc420de6ffe914091a4526c522d/sites/default/settings.php#L254) 
and salt [here](https://github.com/oda-hub/frontend-drupal7-for-astrooda/blob/7ef15ee33477edc420de6ffe914091a4526c522d/sites/default/settings.php#L293) are not in use?

**Comment by volodymyrss** [comment]
Since @motame committed them they might be used by him somewhere.

**Comment by volodymyrss** [comment]
since it is a duplicate I close
