### ISSUE TITLE
Dev instance of mmoda not available

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-chart#15]
I wanted to update the known issues, but I cannot access. 

Please update the URL

![image](https://user-images.githubusercontent.com/2527219/133464367-7699ce39-cfb2-42d8-8cab-5d993d35cc3b.png)

![image](https://user-images.githubusercontent.com/2527219/133464506-19c12c23-8564-4be3-9f04-4a0188ab2c44.png)

**Comment by volodymyrss** [comment]
It looks available now.

Please note this is issue is not related to the astrooda code, and issues like this should be created in redmine. Or in https://github.com/oda-hub/doc-review-guidelines/ for classification.

If you find the issue is still present, please recreate in redmine.

**Comment by volodymyrss** [comment]
@motame did you intentionally re-open it?

**Comment by motame** [comment]
Yes ! indeed.
Carlo, the dec instance is not yet ready for the update of the help pages.
It should be OK by Monday morning.
I'm still updating that part !
Changing all links to images, path aliases, book outline, etc.

**Comment by volodymyrss** [comment]
Alright. I recreated it here https://redmine.astro.unige.ch/issues/25062
Let us not create issues related to particular platform deployments in the code repository.
