### ISSUE TITLE
add image_allow_insecure_derivatives

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-chart#23]
this:

```php
$conf['image_allow_insecure_derivatives'] = TRUE;
```

following https://github.com/oda-hub/mmoda-frontend-module/pull/157#issuecomment-1129907501

**Comment by dsavchenko** [comment]
It's already there https://github.com/oda-hub/frontend-chart/blob/60de3dfc4c15f99efda5e1b097cd41b34d5eaa1a/config/drupal7_sites_default_settings.php.template#L656

**Comment by volodymyrss** [comment]
@motame apparently, the option is already there! So it's set in production, staging, APC, etc. Is anything else needed?
